name: fenix
description: 'A new Flutter project.'
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # state management
  flutter_bloc: ^9.0.0

  # functional programming
  dartz: ^0.10.1

  # dependency injection
  injectable: ^2.5.0
  get_it: ^8.0.3

  # equatable
  equatable: ^2.0.7

  # network
  dio: ^5.7.0
  retrofit: ^4.4.2

  # localization
  easy_localization: ^3.0.7

  # router
  auto_route: ^9.3.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  auto_route_generator: ^9.3.1
  build_runner: ^2.4.14
  retrofit_generator: ^9.1.7
  injectable_generator: ^2.7.0

flutter:
  uses-material-design: true
